name: Mobileraker companion
version: 0.5.0.0
description: Companion for Mobileraker
url: https://github.com/dimquea/hassio/tree/main/mobileraker_companion
slug: mobileraker_companion
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
udev: true
map:
  - addon_config:rw
boot: auto
options:
  printers: []
schema:
  printers:
    - name: str
      moonraker_uri: str
      moonraker_api_key: str?
